'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from "./components"
import Provider from './Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pinterest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header routerPaths={{
            asPath: '',
            push: function (path: string): void {
              throw new Error('Function not implemented.')
            }
          }} />
          {children}
        </Provider>
      </body>
    </html>
  )
}
